### ISSUE TITLE
Two-Way ANOVA: 'Substract' did not contain a loop with signature matching types

### ISSUE THREAD

**Issue by clementpoiret** [raphaelvallat/pingouin#16]
Good morning.

I'm trying to do a two-way ANOVA. My dataset is looking like this:

```
gender success d t v 
M      TRUE    1 1 2
M      FALSE   1 2 7
F      TRUE    1 2 1
M      TRUE    3 5 4
F      FALSE   2 1 6
```

Gender and Success are my between variables.

So I'm doing: 
`pg.anova(dv=v, between=["gender", "success"], data=output, detailed=False)`

And I got this error:
```
Traceback (most recent call last):

  File "<ipython-input-93-35b88e82087c>", line 8, in <module>
    print(pg.anova(dv=v, between=["gender", "success"], data=output, detailed=False), "\n")

  File "C:\Users\poire\Anaconda3\lib\site-packages\pingouin\parametric.py", line 801, in anova
    export_filename=export_filename)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pingouin\parametric.py", line 939, in anova2
    ss_resid = np.sum(data.groupby([fac1, fac2]).apply(lambda x:

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 701, in apply
    return self._python_apply_general(f)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 707, in _python_apply_general
    self.axis)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 190, in apply
    res = f(group)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pingouin\parametric.py", line 940, in <lambda>
    (x - x.mean())**2))[0]

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 2030, in f
    level=level)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1930, in _combine_series_frame
    return self._combine_match_columns(other, func, level=level)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\frame.py", line 5116, in _combine_match_columns
    return ops.dispatch_to_series(left, right, func, axis="columns")

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1157, in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 123, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 68, in _evaluate_standard
    return op(a, b)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1144, in column_op
    for i in range(len(a.columns))}

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1144, in <dictcomp>
    for i in range(len(a.columns))}

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1583, in wrapper
    result = safe_na_op(lvalues, rvalues)

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1533, in safe_na_op
    lambda x: op(x, rvalues))

  File "pandas/_libs/algos.pyx", line 690, in pandas._libs.algos.arrmap

  File "C:\Users\poire\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1533, in <lambda>
    lambda x: op(x, rvalues))

TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```

If I remove either gender or success, the code is working well.
Is there any fix?

Thanks,
Clément.

**Comment by raphaelvallat** [comment]
Dear @clementpoiret,
I cannot replicate your error, I've tried your code and it works just fine (see the image below). The most likely explanation is that there is a "str" in your dependent variable, so I would first make sure that `v` is numeric with `output['v'] = pd.to_numeric(output['v'])`. Please also make sure that you have the latest version of Pingouin and Pandas (and Python >= 3.5).

![test](https://user-images.githubusercontent.com/25703792/56676487-410aa680-6673-11e9-9b47-115ab350815a.png)

Hope this helps!
Raphael

**Comment by clementpoiret** [comment]
Thanks for your answer Raphael. Unfortunately, all of my columns are float64.
Here is my csv : https://pastebin.com/RZvk56Dg

I made a really simple code printing dtype of my variables, and I tried to do an Anova. I have the pingouin 0.2.4 : 
![Code](https://i.imgur.com/LghyEI3.png)

**Comment by raphaelvallat** [comment]
Thanks @clementpoiret ! Ok so you're right, I realized that there are several mistakes in the `pg.anova2` function (all the other ANOVA functions have been tested against R and JASP but not this one).

I'll have to fix the code and publish a new release asap, but in the meantime I suggest that you run the two-way ANOVA using statsmodels, R, or JASP.

Sorry about that and thanks for pointing out the error!
Raphael

**Comment by raphaelvallat** [comment]
HI @clementpoiret ! Quick update. So the issue was that in the case of **unbalanced** two-way ANOVA (e.g. your dataset), the sums of squares were not properly computed, hence your error. I have solved this error in the latest commit: the `pg.anova` function will now make an internal call to statsmodels when the groups have unequal sample sizes. For now, this is only on the _develop_ branch of Pingouin, so if you want to install it you'll need to git clone the repository. But I will definitely release a new version of Pingouin in the next few days.

Please find below a screenshot of the correct two-way ANOVA. The results have been tested against R and JASP.

![anova2](https://user-images.githubusercontent.com/25703792/56777194-fe38f380-6784-11e9-88ac-43eeae2e2a93.PNG)

Thanks again,
Raphael

**Comment by clementpoiret** [comment]
Thanks to you for your hard work! You already saved me for another work for Mixed Model Anova, your lib is fantastic :)

**Comment by raphaelvallat** [comment]
Merci beaucoup Clement :-) -- really appreciate your kind words!
