### ISSUE TITLE
TestParametric::test_pandas fails with dtype mismatch on 32-bit platforms

### ISSUE THREAD

**Issue by musicinmybrain** [raphaelvallat/pingouin#197]
I’m helping to update the `python-pingouin` package in Fedora Linux. One test, `TestParametric::test_pandas`, is failing on 32-bit platforms (`i686` and `armv7hl`). I can’t easily tell if the actual problem here is in `pingouin`, `pandas`, or somewhere else (`scipy`, `pandas-flavor`, …).

```
=================================== FAILURES ===================================
__________________________ TestParametric.test_pandas __________________________
self = <pingouin.tests.test_pandas.TestParametric testMethod=test_pandas>
    def test_pandas(self):
        """Test pandas method.
        """
        # Test the ANOVA (Pandas)
        aov = df.anova(dv='Scores', between='Group', detailed=True)
        assert aov.equals(pg.anova(dv='Scores', between='Group', detailed=True,
                                   data=df))
        aov3_ss1 = df_aov3.anova(dv='Cholesterol', between=['Sex', 'Drug'],
                                 ss_type=1)
        aov3_ss2 = df_aov3.anova(dv='Cholesterol', between=['Sex', 'Drug'],
                                 ss_type=2)
        aov3_ss2_pg = pg.anova(dv='Cholesterol', between=['Sex', 'Drug'],
                               data=df_aov3, ss_type=2)
        assert not aov3_ss1.equals(aov3_ss2)
        assert aov3_ss2.round(3).equals(aov3_ss2_pg.round(3))
    
        # Test the Welch ANOVA (Pandas)
        aov = df.welch_anova(dv='Scores', between='Group')
        assert aov.equals(pg.welch_anova(dv='Scores', between='Group',
                                         data=df))
    
        # Test the ANCOVA
        aov = df_anc.ancova(dv='Scores', covar='Income',
                            between='Method').round(3)
        assert aov.equals(pg.ancova(data=df_anc, dv='Scores', covar='Income',
                          between='Method').round(3))
    
        # Test the repeated measures ANOVA (Pandas)
        aov = df.rm_anova(dv='Scores', within='Time', subject='Subject',
                          detailed=True)
        assert aov.equals(pg.rm_anova(dv='Scores', within='Time',
                                      subject='Subject',
                                      detailed=True, data=df))
    
        # FDR-corrected post hocs with Hedges'g effect size
        ttests = df.pairwise_ttests(dv='Scores', within='Time',
                                    subject='Subject', padjust='fdr_bh',
                                    effsize='hedges')
        assert ttests.equals(pg.pairwise_ttests(dv='Scores', within='Time',
                                                subject='Subject',
                                                padjust='fdr_bh',
                                                effsize='hedges', data=df))
    
        # Pairwise Tukey
        tukey = df.pairwise_tukey(dv='Scores', between='Group')
        assert tukey.equals(pg.pairwise_tukey(data=df, dv='Scores',
                                              between='Group'))
    
        # Test two-way mixed ANOVA
        aov = df.mixed_anova(dv='Scores', between='Group', within='Time',
                             subject='Subject', correction=False)
        assert aov.equals(pg.mixed_anova(dv='Scores', between='Group',
                                         within='Time',
                                         subject='Subject', correction=False,
                                         data=df))
    
        # Test parwise correlations
        corrs = data.pairwise_corr(columns=['X', 'M', 'Y'], method='spearman')
        corrs2 = pg.pairwise_corr(data=data, columns=['X', 'M', 'Y'],
                                  method='spearman')
        assert corrs['r'].equals(corrs2['r'])
    
        # Test partial correlation
        corrs = data.partial_corr(x='X', y='Y', covar='M', method='spearman')
        corrs2 = pg.partial_corr(x='X', y='Y', covar='M', method='spearman',
                                 data=data)
        assert corrs['r'].equals(corrs2['r'])
    
        # Test partial correlation matrix (compare with the ppcor package)
        corrs = data.iloc[:, :5].pcorr().round(3)
        np.testing.assert_array_equal(corrs.iloc[0, :].to_numpy(),
                                      [1, 0.392, 0.06, -0.014, -0.149])
        # Now compare against Pingouin's own partial_corr function
        corrs = data[['X', 'Y', 'M']].pcorr()
        corrs2 = data.partial_corr(x='X', y='Y', covar='M')
        assert np.isclose(corrs.at['X', 'Y'], corrs2.at['pearson', 'r'])
    
        # Test rcorr (correlation matrix with p-values)
        # We compare against Pingouin pairwise_corr function
        corrs = df_corr.rcorr(padjust='holm', decimals=4)
        corrs2 = df_corr.pairwise_corr(padjust='holm').round(4)
        assert corrs.at['Neuroticism', 'Agreeableness'] == '*'
        assert (corrs.at['Agreeableness', 'Neuroticism'] ==
                str(corrs2.at[2, 'r']))
        corrs = df_corr.rcorr(padjust='holm', stars=False, decimals=4)
        assert (corrs.at['Neuroticism', 'Agreeableness'] ==
                str(corrs2.at[2, 'p-corr'].round(4)))
        corrs = df_corr.rcorr(upper='n', decimals=5)
        corrs2 = df_corr.pairwise_corr().round(5)
        assert corrs.at['Extraversion', 'Openness'] == corrs2.at[4, 'n']
        assert corrs.at['Openness', 'Extraversion'] == str(corrs2.at[4, 'r'])
        # Method = spearman does not work with Python 3.5 on Travis?
        # Instead it seems to return the Pearson correlation!
>       df_corr.rcorr(method='spearman')
aov        =         Source        SS  DF1  DF2  ...         F     p-unc       np2       eps
0        Group  5.459963    1   58  ......064929  0.998751
2  Interaction  5.167192    2  116  ...  2.727996  0.069545  0.044922       NaN
[3 rows x 9 columns]
aov3_ss1   =        Source         SS    DF        MS         F     p-unc       np2
0         Sex   3.362769   1.0  3.362769  3.461...62   2.0  0.561181  0.577636  0.564168  0.018007
3    Residual  61.205378  63.0  0.971514       NaN       NaN       NaN
aov3_ss2   =        Source         SS    DF        MS         F     p-unc       np2
0         Sex   3.419789   1.0  3.419789  3.520...62   2.0  0.561181  0.577636  0.564168  0.018007
3    Residual  61.205378  63.0  0.971514       NaN       NaN       NaN
aov3_ss2_pg =        Source         SS    DF        MS         F     p-unc       np2
0         Sex   3.419789   1.0  3.419789  3.520...62   2.0  0.561181  0.577636  0.564168  0.018007
3    Residual  61.205378  63.0  0.971514       NaN       NaN       NaN
corrs      =                   Neuroticism Extraversion  ... Agreeableness Conscientiousness
Neuroticism                 -         ...              500
Conscientiousness    -0.36801      0.06459  ...       0.15867                 -
[5 rows x 5 columns]
corrs2     =                X                  Y   method  ...    p-unc       BF10    power
0    Neuroticism       Extraversion  pe...  0.059  0.06035
9  Agreeableness  Conscientiousness  pearson  ...  0.00037     31.243  0.94638
[10 rows x 10 columns]
self       = <pingouin.tests.test_pandas.TestParametric testMethod=test_pandas>
ttests     =   Contrast        A        B  Paired  ...    p-corr  p-adjust   BF10    hedges
0     Time   August  January    True  ....  4.232 -0.482547
2     Time  January     June    True  ...  0.310194    fdr_bh  0.232 -0.169520
[3 rows x 13 columns]
tukey      =          A           B   mean(A)  ...         T   p-tukey    hedges
0  Control  Meditation  5.567851  ... -2.289903  0.023202 -0.339918
[1 rows x 9 columns]
pingouin/tests/test_pandas.py:114: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.10/site-packages/pandas_flavor/register.py:29: in __call__
    return method(self._obj, *args, **kwargs)
        args       = ()
        kwargs     = {'method': 'spearman'}
        method     = <function rcorr at 0xbb3880b8>
        self       = <pandas_flavor.register.register_dataframe_method.<locals>.inner.<locals>.AccessorMethod object at 0xa8881f10>
pingouin/correlation.py:1050: in rcorr
    mat = self.corr(method=method).round(decimals)
        decimals   = 3
        ffp        = <function format_float_positional at 0xc3ab3028>
        method     = 'spearman'
        padjust    = None
        pearsonr   = <function pearsonr at 0xbbb59e38>
        pval_stars = {0.001: '***', 0.01: '**', 0.05: '*'}
        self       =      Neuroticism  Extraversion  Openness  Agreeableness  Conscientiousness
0        2.47917       4.20833   3.93750   ...3            3.39583
499      2.54167       3.56250   3.14583        3.45833            2.89583
[500 rows x 5 columns]
        spearmanr  = <function spearmanr at 0xbbb5f388>
        stars      = True
        tif        = <function triu_indices_from at 0xc39efcd0>
        upper      = 'pval'
/usr/lib/python3.10/site-packages/pandas/core/frame.py:9376: in corr
    correl = libalgos.nancorr_spearman(mat, minp=min_periods)
        cols       = Index(['Neuroticism', 'Extraversion', 'Openness', 'Agreeableness',
       'Conscientiousness'],
      dtype='object')
        idx        = Index(['Neuroticism', 'Extraversion', 'Openness', 'Agreeableness',
       'Conscientiousness'],
      dtype='object')
        mat        = array([[2.47917, 4.20833, 3.9375 , 3.95833, 3.45833],
       [2.60417, 3.1875 , 3.95833, 3.39583, 3.22917],
       [2.... 3.     ],
       [2.08333, 3.66667, 3.58333, 3.45833, 3.39583],
       [2.54167, 3.5625 , 3.14583, 3.45833, 2.89583]])
        method     = 'spearman'
        min_periods = 1
        numeric_df =      Neuroticism  Extraversion  Openness  Agreeableness  Conscientiousness
0        2.47917       4.20833   3.93750   ...3            3.39583
499      2.54167       3.56250   3.14583        3.45833            2.89583
[500 rows x 5 columns]
        self       =      Neuroticism  Extraversion  Openness  Agreeableness  Conscientiousness
0        2.47917       4.20833   3.93750   ...3            3.39583
499      2.54167       3.56250   3.14583        3.45833            2.89583
[500 rows x 5 columns]
pandas/_libs/algos.pyx:415: in pandas._libs.algos.nancorr_spearman
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   ValueError: Buffer dtype mismatch, expected 'const intp_t' but got 'long long'
pandas/_libs/algos.pyx:938: ValueError
```

On 32-bit Linux platforms, `long long` is normally 64-bit but `intp_t` is 32-bit, which explains what is happening but not why it is happening.

I can easily do any tests that are needed on these platforms to try to figure out where the root issue is, but some ideas regarding what to look for would be very helpful.

**Comment by raphaelvallat** [comment]
Hi @musicinmybrain,

It seems like the error is in Pandas, specifically when calling `pandas.DataFrame.corr(method="spearman")`. Maybe there is an invalid type change when calculating the ranks for the Spearman correlation? Anyway, I'm not sure there's anything we can do in the source code of Pingouin to fix this. For reference, the issue comes from this line:

https://github.com/raphaelvallat/pingouin/blob/30030d5c2809bb7b1f4423bb4b86e270e7aec8fc/pingouin/correlation.py#L1050

**Comment by musicinmybrain** [comment]
Thanks. I’ll try to run down a reproducible example involving only Pandas when I have more time to dig into it. If I can get that far, I should be able to find the root cause and propose a fix for Pandas. It might take a little while, though.

**Comment by musicinmybrain** [comment]
Wow, that was easy.

On a 64-bit platform:
```
>>> from pandas import DataFrame
>>> DataFrame([1.0, 2,0]).corr('spearman')
     0
0  1.0
```

On a 32-bit platform:
```
>>> from pandas import DataFrame
>>> DataFrame([1.0, 2.0]).corr('spearman')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pandas/core/frame.py", line 9376, in corr
    correl = libalgos.nancorr_spearman(mat, minp=min_periods)
  File "pandas/_libs/algos.pyx", line 415, in pandas._libs.algos.nancorr_spearman
  File "pandas/_libs/algos.pyx", line 938, in pandas._libs.algos.rank_1d
ValueError: Buffer dtype mismatch, expected 'const intp_t' but got 'long long'
```

Definitely a Pandas bug. I’ll report it upstream there, and perhaps work on a fix.

**Comment by musicinmybrain** [comment]
When Pandas 1.3.4 is released, it should contain the fix for this bug.

**Comment by raphaelvallat** [comment]
Perfect, let us know. However, we'll have to wait at least a few months before updating the dependencies to pandas>=1.3.4

**Comment by raphaelvallat** [comment]
Any updates on this? Thanks!

**Comment by musicinmybrain** [comment]
I haven’t tested with 1.3.4 because the Fedora package for Pandas is still behind; the primary maintainer has been overwhelmed by life events and semi-responsive. I’m planning to send a PR to update the Pandas package and try to get it merged, but I haven’t had a chance.

In the unlikely case that Pandas ≥1.3.4 isn’t a fix, I’ll revisit this issue when I get to test with it. Otherwise, please assume all is well!
