### ISSUE TITLE
pandas fails with dtype mismatch on 32-bit platforms

### ISSUE THREAD

**Issue by scinteeb** [raphaelvallat/pingouin#378]
Hello,
I am trying to use pandas on a ARMv7 CPU in a Yocto distribution. The version that I am able to compile in Yocto used is 1.4.2. The issue is related to reading a simple csv file
"H1,H2,H3,H4,H5
1,2,3,4,5"
and the code is as simple as 
_import pandas as pd
df = pd.read_csv("data.csv")
print(df.info())_

The error that I got is:
Traceback (most recent call last):
  File "/home/root/test.py", line 3, in <module>
    print(df.info())
  File "/usr/lib/python3.10/site-packages/pandas/core/frame.py", line 3171, in info
    info.render(
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 524, in render
    printer.to_buffer(buf)
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 597, in to_buffer
    table_builder = self._create_table_builder()
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 683, in _create_table_builder
    return DataFrameTableBuilderVerbose(
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 963, in __init__
    self.strrows: Sequence[Sequence[str]] = list(self._gen_rows())
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 998, in _gen_rows_with_counts
    yield from zip(
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 946, in _gen_dtypes
    for dtype in self.dtypes:
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 751, in dtypes
    return self.info.dtypes
  File "/usr/lib/python3.10/site-packages/pandas/io/formats/info.py", line 478, in dtypes
    return self.data.dtypes
  File "/usr/lib/python3.10/site-packages/pandas/core/generic.py", line 5746, in dtypes
    data = self._mgr.get_dtypes()
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 228, in get_dtypes
    return dtypes.take(self.blknos)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 168, in blknos
    self._rebuild_blknos_and_blklocs()
  File "pandas/_libs/internals.pyx", line 711, in pandas._libs.internals.BlockManager._rebuild_blknos_and_blklocs
ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long long'

It looks like dataframe object is malformed. As a mater of fact, even constructing a simple dataframe object and trying to print it leads to the same issue.

Any feedback is much appreciated.

**Comment by scinteeb** [comment]
Sorry guys! I placed the bug in the wrong project. I apologize!
