### ISSUE TITLE
relimp_perc causing TypeError: unsupported operand type(s) for /: 'list' and 'int'

### ISSUE THREAD

**Issue by loganlongacre** [raphaelvallat/pingouin#399]
full traceback:
```
Traceback (most recent call last):
  File "file.py", line 111, in <module>
    linreg = pg.linear_regression(dframe[['EIS','RH700','omega700','SST']], dframe['LCF'], relimp=True)
  File "/miniconda3/envs/pythonProject/lib/python3.10/site-packages/pingouin/regression.py", line 488, in linear_regression
    reli = _relimp(data.drop(columns=["Intercept"]).cov(numeric_only=True))
  File "/miniconda3/envs/pythonProject/lib/python3.10/site-packages/pingouin/regression.py", line 596, in _relimp
    "relimp_perc": all_preds / sum(all_preds) * 100,
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```
i fixed this in my install by changing line 596 in regression.py from
```
"relimp_perc": all_preds / sum(all_preds) * 100
```
to
```
"relimp_perc": [(x / sum(all_preds) * 100) for x in all_preds]
```
this probably isn't the most computationally efficient for a release but it works for me.

**Comment by raphaelvallat** [comment]
A simple conversion from list to a np.array does the trick. Implemented in https://github.com/raphaelvallat/pingouin/commit/d26af454b74688e5f1c579715d175fa5cfce6229
