### ISSUE TITLE
Request: Support for MultiIndex columns

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#5]
I typically end up having `MultiIndex` columns in my `DataFrame`s during analysis, which currently does not seem to be (well) supported by `pingouin`. Here's an example when trying to use `pairwise_corr()` on `MultiIndex` columns:

```python
In[31]: import pandas as pd
   ...: 
   ...: 
   ...: results_a = list(range(5))
   ...: results_b = list(range(5))
   ...: 
   ...: columns = pd.MultiIndex.from_tuples([('Result', 'a'),
   ...:                                      ('Result', 'b')])
   ...: data = pd.DataFrame(dict(a=results_a, b=results_b))
   ...: data.columns = columns
   ...: 
   ...: print(data)
   ...: 
  Result   
       a  b
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4

```

```python
In[32]: import pingouin
   ...: pingouin.pairwise_corr(data, columns=[('Result', 'a'),
   ...:                                       ('Result', 'b')])
   ...: 
Traceback (most recent call last):
  File "/Users/hoechenberger/miniconda3/envs/QUOTE/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-f548ba39714e>", line 3, in <module>
    ('Result', 'b')])
  File "/Users/hoechenberger/miniconda3/envs/QUOTE/lib/python3.7/site-packages/pingouin/pairwise.py", line 818, in pairwise_corr
    assert comb[0] in keys
AssertionError
```

In this specific case, this behavior is caused because [`np.intersect1d(keys, columns)`](https://github.com/raphaelvallat/pingouin/blob/cfbbb71b27566d4683b1b819fd31ee3e6accfd42/pingouin/pairwise.py#L806) returns `array(['Result', 'a', 'b'], dtype='<U6')`, which then yields the combinations `[('Result', 'a'), ('Result', 'b'), ('a', 'b')]`; of course, these don't make much sense.

Would be nice if `pingouin` could handle `MultiIndex` columns directly.

**Comment by hoechenberger** [comment]
My current workaround:
```python
In[3]: corr_result = pingouin.pairwise_corr(data['Result'], columns=['a', 'b'])
  ...: print(corr_result)
  ...: 
/Users/hoechenberger/miniconda3/envs/QUOTE/lib/python3.7/site-packages/pingouin/effsize.py:135: RuntimeWarning: divide by zero encountered in arctanh
  z = np.arctanh(stat)
/Users/hoechenberger/miniconda3/envs/QUOTE/lib/python3.7/site-packages/pingouin/power.py:618: RuntimeWarning: divide by zero encountered in arctanh
  zr = np.arctanh(r) + r / (2 * (n - 1))
/Users/hoechenberger/miniconda3/envs/QUOTE/lib/python3.7/site-packages/scipy/integrate/quadpack.py:385: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)
/Users/hoechenberger/miniconda3/envs/QUOTE/lib/python3.7/site-packages/pingouin/pairwise.py:854: RuntimeWarning: divide by zero encountered in arctanh
  stats['z'] = np.arctanh(stats['r'].values)
   X  Y   method       tail  n  ...    adj_r2    z  p-unc   BF10  power
0  a  b  pearson  two-sided  5  ...       1.0  inf    0.0 -8.554    1.0

[1 rows x 13 columns]
```

**Comment by raphaelvallat** [comment]
Hi @hoechenberger! 
I've just added suport for multi-index columns in the pingouin.pairwise_corr function (commit https://github.com/raphaelvallat/pingouin/commit/94da5e6495ba9218362da409e09f65c0714904bd).

This will be hopefully included in the next release. If by any chance you can give it a try on "real-data" before and report any bugs that would be greatly appreciated. Some examples are shown in the Jupyter notebook https://github.com/raphaelvallat/pingouin/blob/94da5e6495ba9218362da409e09f65c0714904bd/notebooks/04_Correlations.ipynb

Thanks!
Raphael
